### ISSUE TITLE
如何解密出dts文件

### ISSUE THREAD

**Issue by Catversewww** [HorseLuke/openwrt-ruijie-x32-pro-note#1]
你好，我看README里提到可以从系统升级镜像中提取dts文件，但是我在尝试的时候发现升级镜像是加密的，然后就没有头绪了。可以问一下你是怎么从升级镜像中提取文件的吗？

**Comment by HorseLuke** [comment]
通过锐捷的一个加解密程序获取的，但是那个工具我也丢失了。拆出路由器直接dump存储芯片里面的rom也可以获取。

**Comment by Catversewww** [comment]
好的，感谢！
